// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIza...', // You'll need to replace this with the actual API key for attendwise2
    appId: 'com.hackerspace.my_app',
    messagingSenderId: '000000000000', // Replace with actual sender ID
    projectId: 'attendwise2',
    storageBucket: 'attendwise2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:
        'AIza...', // You'll need to replace this with the actual API key for attendwise2
    appId: 'com.example.myApp',
    messagingSenderId: '000000000000', // Replace with actual sender ID
    projectId: 'attendwise2',
    storageBucket: 'attendwise2.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIza...', // You'll need to replace this with the actual API key for attendwise2
    appId: 'my_app',
    messagingSenderId: '000000000000', // Replace with actual sender ID
    projectId: 'attendwise2',
    storageBucket: 'attendwise2.appspot.com',
    authDomain: 'attendwise2.firebaseapp.com',
  );
}
