// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNpEZAsybnA0G9DNuGqO5L8dFXjvGbQs4',
    appId: '1:995671720434:android:56e4c4a7f59b8f8f4cc511',
    messagingSenderId: '995671720434',
    projectId: 'attendwise2',
    storageBucket: 'attendwise2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLbluKp5d08t-VA5lPsQXJNXmGGgRrWYs',
    appId: '1:995671720434:ios:7eb1b7c88cc5dca34cc511',
    messagingSenderId: '995671720434',
    projectId: 'attendwise2',
    storageBucket: 'attendwise2.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVS3aJDBP4cKVLNmIXDSzJf2pv7L7RhXY',
    appId: '1:995671720434:web:a5e4d2daeca08ad14cc511',
    messagingSenderId: '995671720434',
    projectId: 'attendwise2',
    storageBucket: 'attendwise2.appspot.com',
    authDomain: 'attendwise2.firebaseapp.com',
  );
}
